name: Docker Multi-Image Build & Security Audit

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-test-containers:
    name: Build Multi-Stage Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Build Backend Gateway Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: false
          tags: fraudguard-backend:latest

      - name: Build Simulator Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.simulator
          push: false
          tags: fraudguard-simulator:latest
